theme: jekyll-theme-architect
title: Welcome to My Hive Monitor Project Page!
description: This page will be used to document my Honey Bee Hive Monitoring System
<!-- blank line -->
<figure class="video_container">
  <iframe src="http://admin:123456@kyserike.mynetgear.com:500/mjpeg/stream.cgi?chn=0" frameborder="0" allowfullscreen="true"> </iframe>
</figure>
<!-- blank line -->
